# development:
# url: neo4j://localhost:7687
#     username: neo4j
#     password: password
#     encryption: false


development:
  url: http://localhost:7474
  username: neo4j
  password: password

# test:
#   url: http://localhost:7474
#   username: neo4j
#   password: your_password
#
# production:
#   url: <%= ENV['NEO4J_URL'] %>
#   username: <%= ENV['NEO4J_USERNAME'] %>
#   password: <%= ENV['NEO4J_PASSWORD'] %>
